name: My First CI

on: 
    push:
        branches: main
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Azure ACR Login
                uses: azure/login@v1
                with:
                    registry: <registry-name>.azurecr.io
                    client_id: ${{ vars.AZURE_CLIENT_ID }}
                    password: ${{ secrets.AZURE_CLIENT_SECRETS }}
                    tenant-id: ${{ vars.AZURE_TENANT_ID }}
                    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}