name: My First CI

on: 
    push:
        branches: main
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   
                name: Docker Login
                uses: docker/login-action@v3
                with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                    

            - 
                name: Build and Push
                uses: docker/build-push-action@v5
        
                with:
                    dockerfile: Dockerfile
                    context: . 
                    run: docker build --tag solar-system:$GITHUB_SHA .
                    push: false
                      
                   
            -   name: Run Docker Container
                run: |
                      docker run --name solar-system -d \
                        -p 3000:3000 \
                        -e MONGO_URI=$MONGO_URI \
                        -e MONGO_USERNAME=$MONGO_USERNAME \
                        -e MONGO_PASSWORD=$MONGO_PASSWORD \
                        solar-system:$GITHUB_SHA
            
        
            -   name: Wait for Docker Container to Start
                run: sleep 10
        
            -   name: Test Docker Image
                run: |
                      docker ps -a
                      wget -q -O - http://127.0.0.1:3000/live | grep live